# Site settings
title: Abel‘s Blog
SEOTitle: Abel Joo 的博客 | Abel's Blog
header-img: img/home-bg.jpg
# email: x@gmail.com
description: "当你停止创造，你的才能就不再重要，剩下的只有品味，品味会排斥其他人，让你变得更狭隘，所以，要创造。"
keyword: "朱嘉俊, 嘉俊, abel, abel joo, 爱宝, @abel, 嘉俊的博客, 朱嘉俊的博客, 爱宝的博客, abel Blog, abel's Blog, abel joo Blog, 互联网, android, 安卓, 机器学习, ML, machine learning, DL, deep learning"
url: "https://abeljoo.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     
# zhihu_username:     Abel_Joo
# github_username:    AbelJoo
# twitter_username:   
#facebook_username:  
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: abeljoo-com

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-140077664-1'            # Format: UA-xxxxxx-xx
ga_domain: abeljoo.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Ashes to ashes, dust to dust.<br>终究不过是楼高楼矮，<br>人多人少的区别。"
sidebar-avatar: /img/avatar_abel.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
# friends: [
#     {
#     #     title: "a",
#     #     href: "http://a.a/"
#     # },{
        
#     }
# ]
